In [3]:
import tensorflow as tf

In [ ]:
#conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch

# Tensors
 A kind of data structure -> multidimentional arrays or metrics with tensor you can encode all your parameters

In [1]:
conda install pytorch torchvision torchaudio cpuonly -c pytorch

Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Solving environment: ...working... done

## Package Plan ##

  environment location: D:\DLCVANLP\ComputerVision-ObjectDetection\env

  added / updated specs:
    - cpuonly
    - pytorch
    - torchaudio
    - torchvision


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cpuonly-2.0                |                0           2 KB  pytorch
    pytorch-1.10.2             |      py3.7_cpu_0       193.4 MB  pytorch
    pytorch-mutex-1.0          |              cpu           3 KB  pytorch
    torchaudio-0.10.2          |         py37_cpu         2.1 MB  pytorch
    torchvision-0.11.3         |         py37_cpu         7.2 MB  pytorch
    --------------------------------------

pytorch-1.10.2       | 193.4 MB  | ##1        |  21% 
pytorch-1.10.2       | 193.4 MB  | ##1        |  21% 
pytorch-1.10.2       | 193.4 MB  | ##1        |  21% 
pytorch-1.10.2       | 193.4 MB  | ##1        |  22% 
pytorch-1.10.2       | 193.4 MB  | ##1        |  22% 
pytorch-1.10.2       | 193.4 MB  | ##1        |  22% 
pytorch-1.10.2       | 193.4 MB  | ##1        |  22% 
pytorch-1.10.2       | 193.4 MB  | ##2        |  22% 
pytorch-1.10.2       | 193.4 MB  | ##2        |  22% 
pytorch-1.10.2       | 193.4 MB  | ##2        |  22% 
pytorch-1.10.2       | 193.4 MB  | ##2        |  22% 
pytorch-1.10.2       | 193.4 MB  | ##2        |  23% 
pytorch-1.10.2       | 193.4 MB  | ##2        |  23% 
pytorch-1.10.2       | 193.4 MB  | ##2        |  23% 
pytorch-1.10.2       | 193.4 MB  | ##3        |  23% 
pytorch-1.10.2       | 193.4 MB  | ##3        |  23% 
pytorch-1.10.2       | 193.4 MB  | ##3        |  23% 
pytorch-1.10.2       | 193.4 MB  | ##3        |  23% 
pytorch-1.10.2       | 193.4

pytorch-1.10.2       | 193.4 MB  | #########9 |  99% 
pytorch-1.10.2       | 193.4 MB  | #########9 |  99% 
pytorch-1.10.2       | 193.4 MB  | #########9 |  99% 
pytorch-1.10.2       | 193.4 MB  | #########9 |  99% 
pytorch-1.10.2       | 193.4 MB  | #########9 | 100% 
pytorch-1.10.2       | 193.4 MB  | #########9 | 100% 
pytorch-1.10.2       | 193.4 MB  | #########9 | 100% 
pytorch-1.10.2       | 193.4 MB  | ########## | 100% 

torchaudio-0.10.2    | 2.1 MB    |            |   0% 
torchaudio-0.10.2    | 2.1 MB    |            |   1% 
torchaudio-0.10.2    | 2.1 MB    | 2          |   3% 
torchaudio-0.10.2    | 2.1 MB    | 5          |   6% 
torchaudio-0.10.2    | 2.1 MB    | #1         |  12% 
torchaudio-0.10.2    | 2.1 MB    | #7         |  18% 
torchaudio-0.10.2    | 2.1 MB    | ##8        |  29% 
torchaudio-0.10.2    | 2.1 MB    | ####6      |  47% 
torchaudio-0.10.2    | 2.1 MB    | #####7     |  57% 
torchaudio-0.10.2    | 2.1 MB    | ########## | 100% 
torchaudio-0.10.2    | 2.1 

In [2]:
import torch

In [3]:
import numpy as np

In [4]:
data=[[9,10],
     [4,5],
     [12,13]]
tensor_data=torch.tensor(data)

In [6]:
print(tensor_data)

tensor([[ 9, 10],
        [ 4,  5],
        [12, 13]])


In [7]:
print(type(tensor_data))

<class 'torch.Tensor'>


In [8]:
tensor_data[0]

tensor([ 9, 10])

In [9]:
tensor_data[0][0]

tensor(9)

In [10]:
tensor_data[0,0]

tensor(9)

In [11]:
np_data=np.array([[ 9, 10],
        [ 4,  5],
        [12, 13]])

In [12]:
tensor_data_np=torch.tensor(np_data)
print(tensor_data_np)

tensor([[ 9, 10],
        [ 4,  5],
        [12, 13]], dtype=torch.int32)


In [13]:
print(type(tensor_data_np))

<class 'torch.Tensor'>


In [14]:
ones_like_data=torch.ones_like(tensor_data_np)

In [15]:
ones_like_data

tensor([[1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int32)

In [16]:
ones_like_data=torch.ones_like(np_data)

TypeError: ones_like(): argument 'input' (position 1) must be Tensor, not numpy.ndarray

In [17]:
ones_like_data=torch.ones_like(data)

TypeError: ones_like(): argument 'input' (position 1) must be Tensor, not list

In [19]:
ones_like_data_random=torch.rand_like(tensor_data_np)

RuntimeError: "check_uniform_bounds" not implemented for 'Int'

In [20]:
ones_like_data_random=torch.rand_like(tensor_data_np, dtype=torch.float)
ones_like_data_random

tensor([[0.1879, 0.7290],
        [0.1046, 0.9499],
        [0.2855, 0.6984]])

In [22]:
shape=(4,3)
random_tensor=torch.rand(shape)
random_tensor

tensor([[0.2143, 0.7320, 0.7412],
        [0.3081, 0.4433, 0.9821],
        [0.3500, 0.5973, 0.9689],
        [0.3149, 0.6891, 0.3163]])

In [23]:
shape=(4,3,2)
rand_tensor=torch.rand(shape)
rand_tensor

tensor([[[0.6620, 0.5081],
         [0.7427, 0.2086],
         [0.7774, 0.8103]],

        [[0.9848, 0.3198],
         [0.6257, 0.2660],
         [0.9110, 0.7052]],

        [[0.4326, 0.8597],
         [0.8529, 0.1311],
         [0.3769, 0.8790]],

        [[0.9829, 0.7587],
         [0.1384, 0.0893],
         [0.3661, 0.9153]]])

In [24]:
rand_tensor.shape

torch.Size([4, 3, 2])

In [25]:
ones=torch.ones(shape)

In [26]:
ones

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])

In [27]:
zeros=torch.zeros(shape)
zeros

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])

In [28]:
rand_tensor.shape

torch.Size([4, 3, 2])

In [29]:
rand_tensor.dtype

torch.float32

In [30]:
rand_tensor.device

device(type='cpu')

In [31]:
torch.cuda.is_available()

False