# Checkpointing to restore the matrix value

In [2]:
import tensorflow as tf

In [3]:
var1=tf.Variable(5*tf.ones((5,5)))
var1

<tf.Variable 'Variable:0' shape=(5, 5) dtype=float32, numpy=
array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]], dtype=float32)>

In [4]:
ckpt=tf.train.Checkpoint(var=var1)
savepath=ckpt.save("./vars.ckpt")

In [5]:
var1.assign(tf.zeros((5,5)))

<tf.Variable 'UnreadVariable' shape=(5, 5) dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [6]:
var1

<tf.Variable 'Variable:0' shape=(5, 5) dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
ckpt.restore(save)