# Checkpointing to restore the matrix value

In [2]:
import tensorflow as tf

In [3]:
var1=tf.Variable(5*tf.ones((5,5)))
var1

<tf.Variable 'Variable:0' shape=(5, 5) dtype=float32, numpy=
array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]], dtype=float32)>

In [4]:
ckpt=tf.train.Checkpoint(var=var1)
savepath=ckpt.save("./vars.ckpt")

In [5]:
var1.assign(tf.zeros((5,5)))

<tf.Variable 'UnreadVariable' shape=(5, 5) dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [6]:
var1

<tf.Variable 'Variable:0' shape=(5, 5) dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [7]:
ckpt.restore(savepath)

In [8]:
var1

<tf.Variable 'Variable:0' shape=(5, 5) dtype=float32, numpy=
array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]], dtype=float32)>

# tf.function

$ z= x^3 * 6+ y^3 $

In [9]:
def f1(x,y):
    input_var=tf.multiply(x**3,6)+ y**3
    return tf.reduce_mean(input_tensor=input_var)

In [10]:
func=tf.function(f1)

In [11]:
x=tf.constant([3., -4.])
y=tf.constant([1., 4.])

In [12]:
f1(x,y)

<tf.Tensor: shape=(), dtype=float32, numpy=-78.5>

In [13]:
@tf.function ## df decorator function
def f2(x,y):
    input_var=tf.multiply(x**3,6) + y**3
    return tf.reduce_mean(input_tensor=input_var)

In [14]:
f2(x,y)

<tf.Tensor: shape=(), dtype=float32, numpy=-78.5>

In [15]:
def print_me():
    print("Hi FSDS")

In [16]:
print_me()

Hi FSDS


In [19]:
print("**"*20)
print_me()
print("**"*20)

****************************************
Hi FSDS
****************************************


In [23]:
def decorated_it(input_func):
    def decorated_func():
        print("**"*20)
        input_func()
        print("**"*20)
        
    return decorated_func

In [24]:
decorated_func=decorated_it(print_me)
decorated_func()

****************************************
Hi FSDS
****************************************


In [26]:
@decorated_it
def print_me2():
    print("Hi FSDS")

In [27]:
print_me2()

****************************************
Hi FSDS
****************************************


In [28]:
@decorated_it
def print_my_name():
    print("Kul")

In [29]:
print_my_name()

****************************************
Kul
****************************************


# Calculate of Gradient in Tensorflow

In [30]:
x=tf.random.normal(shape=(2,2))
y=tf.random.normal(shape=(2,2))

$ f(x,y) = \sqrt{(x^2 +y^2)}$

$ \nabla f(x,y)=\frac{\partial f}{\partial x} \hat{\imath} + \frac
{\partial f}{\partial y} \hat{\jmath}$

In [31]:
with tf.GradientTape() as tape:
    tape.watch(x)### with respect to x
    f=tf.sqrt(tf.square(x) +tf.square(y))
    df_dx=tape.gradient(f,x)
    print(df_dx)

tf.Tensor(
[[ 0.8200404  -0.46563816]
 [-0.75755364 -0.51135796]], shape=(2, 2), dtype=float32)


In [32]:
with tf.GradientTape() as tape:
    tape.watch(y)# with respect to y
    f=tf.sqrt(tf.square(x)+tf.square(y))
    df_dy=tape.gradient(f,y)
    print(df_dy)

tf.Tensor(
[[ 0.57230574 -0.88497525]
 [-0.652773   -0.85936785]], shape=(2, 2), dtype=float32)


In [34]:
with tf.GradientTape() as tape:
    tape.watch(x)
    tape.watch(y)
    f=tf.sqrt(tf.square(x) +tf.square(y))
    df_dx,df_dy=tape.gradient(f,[x,y])
    print(df_dx)
    print(df_dy)

tf.Tensor(
[[ 0.8200404  -0.46563816]
 [-0.75755364 -0.51135796]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 0.57230574 -0.88497525]
 [-0.652773   -0.85936785]], shape=(2, 2), dtype=float32)


In [36]:
x=tf.Variable(tf.random.normal(shape=(2,2)))
y=tf.Variable(tf.random.normal(shape=(2,2)))

In [37]:
with tf.GradientTape() as tape:
    #tape.watch(x)
   # tape.watch(y)
    f=tf.sqrt(tf.square(x) +tf.square(y))
    df_dx,df_dy=tape.gradient(f,[x,y])
    print(df_dx)
    print(df_dy)

tf.Tensor(
[[ 0.9823198   0.8291688 ]
 [ 0.48610476 -0.9968738 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 0.1872106   0.5589984 ]
 [-0.8739006   0.07901094]], shape=(2, 2), dtype=float32)


In [38]:
x=tf.Variable(3.)
y=tf.Variable(2.)

In [40]:
with tf.GradientTape() as tape:
    f=tf.sqrt(tf.square(x) +tf.square(y))
    df_dx,df_dy=tape.gradient(f,[x,y])
    print(df_dx)
    print(df_dy)

tf.Tensor(0.8320503, shape=(), dtype=float32)
tf.Tensor(0.5547002, shape=(), dtype=float32)


In [41]:
x/tf.sqrt(tf.square(x) +tf.square(y))

<tf.Tensor: shape=(), dtype=float32, numpy=0.8320503>

In [42]:
y/tf.sqrt(tf.square(x) +tf.square(y))

<tf.Tensor: shape=(), dtype=float32, numpy=0.5547002>