In [1]:
import tensorflow as tf

In [3]:
tf.__version__

'2.8.0'

In [4]:
# Tensor Constant
const=tf.constant(43)

In [5]:
const

<tf.Tensor: shape=(), dtype=int32, numpy=43>

In [6]:
const.numpy()

43

In [7]:
const=tf.constant(43, dtype=tf.float32)
const

<tf.Tensor: shape=(), dtype=float32, numpy=43.0>

In [8]:
const.numpy()

43.0

In [9]:
const_matrix=tf.constant([[1,3],[4,5]], dtype=tf.float32)

In [10]:
const_matrix

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 3.],
       [4., 5.]], dtype=float32)>

In [11]:
const_matrix.shape

TensorShape([2, 2])

In [12]:
const_matrix.dtype

tf.float32

In [13]:
const_matrix[0][0]

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [14]:
const_matrix[0][0]=32

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

# Commonly used method

In [16]:
tf.ones(shape=(2,4))

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [17]:
tf.ones(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [18]:
tf.zeros(shape=(2,2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [19]:
const1=tf.constant([[1,2,3],[4,5,6]])
const2=tf.constant([[2,5,3],[3,5,8]])

In [20]:
const1+const2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 3,  7,  6],
       [ 7, 10, 14]])>

In [21]:
tf.add(const1,const2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 3,  7,  6],
       [ 7, 10, 14]])>

## Random constant

In [22]:
tf.random.normal(shape=(2,2), mean=0, stddev=1.0)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.2481412 ,  1.5795301 ],
       [ 0.9190241 ,  0.41928372]], dtype=float32)>

In [23]:
tf.random.uniform(shape=(2,2), minval=0, maxval=10)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[5.040064 , 3.5861182],
       [9.471198 , 3.9955819]], dtype=float32)>

# Variable

In [24]:
var1=tf.Variable([[1,2,3],[4,5,6]])

In [32]:
var1.assign([[22,2,3],[4,5,6]])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[22,  2,  3],
       [ 4,  5,  6]])>

In [30]:
var2=tf.Variable(43)

In [31]:
type(var2)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [26]:
var2.assign(32)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=32>

In [27]:
var2

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=32>

In [28]:
var2=43

In [29]:
type(var2)

int

## Reshaping

In [33]:
tensor=tf.Variable([[22,2,3],[4,5,6]])
tensor.shape

TensorShape([2, 3])

In [36]:
tf.reshape(tensor,[1,6])

<tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[22,  2,  3,  4,  5,  6]])>

In [37]:
tf.reshape(tensor,[2,3])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[22,  2,  3],
       [ 4,  5,  6]])>

In [38]:
tf.reshape(tensor,[6,1])

<tf.Tensor: shape=(6, 1), dtype=int32, numpy=
array([[22],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6]])>

# Broadcasting in TF

In [39]:
tensor

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[22,  2,  3],
       [ 4,  5,  6]])>

In [40]:
scaler=4
4*tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[88,  8, 12],
       [16, 20, 24]])>

In [41]:
scaler*tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[88,  8, 12],
       [16, 20, 24]])>

In [42]:
scaler + tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[26,  6,  7],
       [ 8,  9, 10]])>

# Matrix Multiplication

In [43]:
mat_u=tf.constant([[6,7,7]])
mat_v=tf.constant([[3,4,3]])

In [44]:
mat_u.shape

TensorShape([1, 3])

In [45]:
mat_v.shape

TensorShape([1, 3])

# Rule column of matrix of mat_u=row of matrix mat_v. If you are multiplying mat_u and mat_v

In [46]:
tf.matmul(mat_u, mat_v)

InvalidArgumentError: Matrix size-incompatible: In[0]: [1,3], In[1]: [1,3] [Op:MatMul]

In [47]:
tf.matmul(mat_u, tf.transpose(mat_v))

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[67]])>

In [48]:
tf.matmul(tf.transpose(mat_u), mat_v)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[18, 24, 18],
       [21, 28, 21],
       [21, 28, 21]])>

In [49]:
mat_u@tf.transpose(mat_v)

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[67]])>

In [51]:
# element wise multiplication
mat_u*mat_v

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[18, 28, 21]])>

In [52]:
mat_u.dtype

tf.int32

In [53]:
tf.cast(mat_u, dtype=tf.float32)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[6., 7., 7.]], dtype=float32)>

## Ragged Tensor

#### nested variable length array 

In [54]:
ragged=tf.ragged.constant([[1,2,3,4,5,6],[2],[5,6]])

In [55]:
ragged.shape

TensorShape([3, None])

In [56]:
ragged[0]

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6])>

In [57]:
ragged[0].shape

TensorShape([6])

In [58]:
ragged[1].shape

TensorShape([1])

# Squared differences of Tensor

In [59]:
varx=[2,4,6,8]
vary=2
tf.math.squared_difference(varx,vary)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 0,  4, 16, 36])>

In [60]:
pred=[1,2,3,4,5,6]
actual=[1,1,1,1,1,1]
tf.math.squared_difference(pred, actual)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 0,  1,  4,  9, 16, 25])>

# calculate mean

In [61]:
num=tf.constant([[1,2],[3,4]], dtype=tf.float32)
num

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [62]:
tf.reduce_mean(num)

<tf.Tensor: shape=(), dtype=float32, numpy=2.5>

In [63]:
tf.reduce_mean(num, axis=0)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 3.], dtype=float32)>

In [64]:
tf.reduce_mean(num, axis=1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.5, 3.5], dtype=float32)>

In [65]:
tf.reduce_mean(num, axis=1, keepdims=True)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.5],
       [3.5]], dtype=float32)>